import 'package:fidel/model/FidelLetter.dart';

final List<FidelLetter> fidelLetters = [
  FidelLetter(
  base: 'ሀ',
  forms: [
    FidelForm(fidel: 'ሀ', phonetic: 'ha'),
    FidelForm(fidel: 'ሁ', phonetic: 'hu'),
    FidelForm(fidel: 'ሂ', phonetic: 'hi'),
    FidelForm(fidel: 'ሃ', phonetic: 'hā'),
    FidelForm(fidel: 'ሄ', phonetic: 'hé'),
    FidelForm(fidel: 'ህ', phonetic: 'he'),
    FidelForm(fidel: 'ሆ', phonetic: 'ho'),
  ],
),
FidelLetter(
  base: 'ለ',
  forms: [
    FidelForm(fidel: 'ለ', phonetic: 'la'),
    FidelForm(fidel: 'ሉ', phonetic: 'lu'),
    FidelForm(fidel: 'ሊ', phonetic: 'li'),
    FidelForm(fidel: 'ላ', phonetic: 'lā'),
    FidelForm(fidel: 'ሌ', phonetic: 'lé'),
    FidelForm(fidel: 'ል', phonetic: 'le'),
    FidelForm(fidel: 'ሎ', phonetic: 'lo'),
  ],
),
FidelLetter(
  base: 'ሐ',
  forms: [
    FidelForm(fidel: 'ሐ', phonetic: 'ḥa'),
    FidelForm(fidel: 'ሑ', phonetic: 'ḥu'),
    FidelForm(fidel: 'ሒ', phonetic: 'ḥi'),
    FidelForm(fidel: 'ሓ', phonetic: 'ḥā'),
    FidelForm(fidel: 'ሔ', phonetic: 'ḥé'),
    FidelForm(fidel: 'ሕ', phonetic: 'ḥe'),
    FidelForm(fidel: 'ሖ', phonetic: 'ḥo'),
  ],
),
FidelLetter(
  base: 'መ',
  forms: [
    FidelForm(fidel: 'መ', phonetic: 'ma'),
    FidelForm(fidel: 'ሙ', phonetic: 'mu'),
    FidelForm(fidel: 'ሚ', phonetic: 'mi'),
    FidelForm(fidel: 'ማ', phonetic: 'mā'),
    FidelForm(fidel: 'ሜ', phonetic: 'mé'),
    FidelForm(fidel: 'ም', phonetic: 'me'),
    FidelForm(fidel: 'ሞ', phonetic: 'mo'),
  ],
),

 FidelLetter(
  base: 'ሠ',
  forms: [
    FidelForm(fidel: 'ሠ', phonetic: 'śa'),
    FidelForm(fidel: 'ሡ', phonetic: 'śu'),
    FidelForm(fidel: 'ሢ', phonetic: 'śi'),
    FidelForm(fidel: 'ሣ', phonetic: 'śā'),
    FidelForm(fidel: 'ሤ', phonetic: 'śé'),
    FidelForm(fidel: 'ሥ', phonetic: 'śe'),
    FidelForm(fidel: 'ሦ', phonetic: 'śo'),
  ],
),
FidelLetter(
  base: 'ረ',
  forms: [
    FidelForm(fidel: 'ረ', phonetic: 'ra'),
    FidelForm(fidel: 'ሩ', phonetic: 'ru'),
    FidelForm(fidel: 'ሪ', phonetic: 'ri'),
    FidelForm(fidel: 'ራ', phonetic: 'rā'),
    FidelForm(fidel: 'ሬ', phonetic: 'ré'),
    FidelForm(fidel: 'ር', phonetic: 're'),
    FidelForm(fidel: 'ሮ', phonetic: 'ro'),
  ],
),
FidelLetter(
  base: 'ሰ',
  forms: [
    FidelForm(fidel: 'ሰ', phonetic: 'sa'),
    FidelForm(fidel: 'ሱ', phonetic: 'su'),
    FidelForm(fidel: 'ሲ', phonetic: 'si'),
    FidelForm(fidel: 'ሳ', phonetic: 'sā'),
    FidelForm(fidel: 'ሴ', phonetic: 'sé'),
    FidelForm(fidel: 'ስ', phonetic: 'se'),
    FidelForm(fidel: 'ሶ', phonetic: 'so'),
  ],
),
FidelLetter(
  base: 'ሸ',
  forms: [
    FidelForm(fidel: 'ሸ', phonetic: 'sha'),
    FidelForm(fidel: 'ሹ', phonetic: 'shu'),
    FidelForm(fidel: 'ሺ', phonetic: 'shi'),
    FidelForm(fidel: 'ሻ', phonetic: 'sha'),
    FidelForm(fidel: 'ሼ', phonetic: 'she'),
    FidelForm(fidel: 'ሽ', phonetic: 'she'),
    FidelForm(fidel: 'ሾ', phonetic: 'sho'),
  ],
),

FidelLetter(
  base: 'ቀ',
  forms: [
    FidelForm(fidel: 'ቀ', phonetic: 'qa'),
    FidelForm(fidel: 'ቁ', phonetic: 'qu'),
    FidelForm(fidel: 'ቂ', phonetic: 'qi'),
    FidelForm(fidel: 'ቃ', phonetic: 'qā'),
    FidelForm(fidel: 'ቄ', phonetic: 'qé'),
    FidelForm(fidel: 'ቅ', phonetic: 'qe'),
    FidelForm(fidel: 'ቆ', phonetic: 'qo'),
  ],
),
FidelLetter(
  base: 'በ',
  forms: [
    FidelForm(fidel: 'በ', phonetic: 'ba'),
    FidelForm(fidel: 'ቡ', phonetic: 'bu'),
    FidelForm(fidel: 'ቢ', phonetic: 'bi'),
    FidelForm(fidel: 'ባ', phonetic: 'bā'),
    FidelForm(fidel: 'ቤ', phonetic: 'bé'),
    FidelForm(fidel: 'ብ', phonetic: 'be'),
    FidelForm(fidel: 'ቦ', phonetic: 'bo'),
  ],
),
FidelLetter(
  base: 'ተ',
  forms: [
    FidelForm(fidel: 'ተ', phonetic: 'ta'),
    FidelForm(fidel: 'ቱ', phonetic: 'tu'),
    FidelForm(fidel: 'ቲ', phonetic: 'ti'),
    FidelForm(fidel: 'ታ', phonetic: 'tā'),
    FidelForm(fidel: 'ቴ', phonetic: 'té'),
    FidelForm(fidel: 'ት', phonetic: 'te'),
    FidelForm(fidel: 'ቶ', phonetic: 'to'),
  ],
),

   FidelLetter(
    base: 'ቸ',
    forms: [
      FidelForm(fidel: 'ቸ', phonetic: 'ča'),
      FidelForm(fidel: 'ቹ', phonetic: 'ču'),
      FidelForm(fidel: 'ቺ', phonetic: 'či'),
      FidelForm(fidel: 'ቻ', phonetic: 'čā'),
      FidelForm(fidel: 'ቼ', phonetic: 'čé'),
      FidelForm(fidel: 'ች', phonetic: 'če'),
      FidelForm(fidel: 'ቾ', phonetic: 'čo'),
    ],
  ),
  FidelLetter(
    base: 'ኀ',
    forms: [
      FidelForm(fidel: 'ኀ', phonetic: 'ha'),
      FidelForm(fidel: 'ኁ', phonetic: 'hu'),
      FidelForm(fidel: 'ኂ', phonetic: 'hi'),
      FidelForm(fidel: 'ኃ', phonetic: 'hā'),
      FidelForm(fidel: 'ኄ', phonetic: 'hé'),
      FidelForm(fidel: 'ኅ', phonetic: 'he'),
      FidelForm(fidel: 'ኆ', phonetic: 'ho'),
    ],
  ),
  FidelLetter(
    base: 'ነ',
    forms: [
      FidelForm(fidel: 'ነ', phonetic: 'na'),
      FidelForm(fidel: 'ኑ', phonetic: 'nu'),
      FidelForm(fidel: 'ኒ', phonetic: 'ni'),
      FidelForm(fidel: 'ና', phonetic: 'nā'),
      FidelForm(fidel: 'ኔ', phonetic: 'né'),
      FidelForm(fidel: 'ን', phonetic: 'ne'),
      FidelForm(fidel: 'ኖ', phonetic: 'no'),
    ],
  ),
  FidelLetter(
    base: 'ኘ',
    forms: [
      FidelForm(fidel: 'ኘ', phonetic: 'ña'),
      FidelForm(fidel: 'ኙ', phonetic: 'ñu'),
      FidelForm(fidel: 'ኚ', phonetic: 'ñi'),
      FidelForm(fidel: 'ኛ', phonetic: 'ñā'),
      FidelForm(fidel: 'ኜ', phonetic: 'ñé'),
      FidelForm(fidel: 'ኝ', phonetic: 'ñe'),
      FidelForm(fidel: 'ኞ', phonetic: 'ño'),
    ],
  ),
  FidelLetter(
    base: 'አ',
    forms: [
      FidelForm(fidel: 'አ', phonetic: 'ʼa'),
      FidelForm(fidel: 'ኡ', phonetic: 'ʼu'),
      FidelForm(fidel: 'ኢ', phonetic: 'ʼi'),
      FidelForm(fidel: 'ኣ', phonetic: 'ʼā'),
      FidelForm(fidel: 'ኤ', phonetic: 'ʼé'),
      FidelForm(fidel: 'እ', phonetic: 'ʼe'),
      FidelForm(fidel: 'ኦ', phonetic: 'ʼo'),
    ],
  ),
  FidelLetter(
    base: 'ከ',
    forms: [
      FidelForm(fidel: 'ከ', phonetic: 'ka'),
      FidelForm(fidel: 'ኩ', phonetic: 'ku'),
      FidelForm(fidel: 'ኪ', phonetic: 'ki'),
      FidelForm(fidel: 'ካ', phonetic: 'kā'),
      FidelForm(fidel: 'ኬ', phonetic: 'ké'),
      FidelForm(fidel: 'ክ', phonetic: 'ke'),
      FidelForm(fidel: 'ኮ', phonetic: 'ko'),
    ],
  ),
  FidelLetter(
    base: 'ኸ',
    forms: [
      FidelForm(fidel: 'ኸ', phonetic: 'xa'),
      FidelForm(fidel: 'ኹ', phonetic: 'xu'),
      FidelForm(fidel: 'ኺ', phonetic: 'xi'),
      FidelForm(fidel: 'ኻ', phonetic: 'xā'),
      FidelForm(fidel: 'ኼ', phonetic: 'xé'),
      FidelForm(fidel: 'ኽ', phonetic: 'xe'),
      FidelForm(fidel: 'ኾ', phonetic: 'xo'),
    ],
  ),
  FidelLetter(
    base: 'ወ',
    forms: [
      FidelForm(fidel: 'ወ', phonetic: 'wa'),
      FidelForm(fidel: 'ዉ', phonetic: 'wu'),
      FidelForm(fidel: 'ዊ', phonetic: 'wi'),
      FidelForm(fidel: 'ዋ', phonetic: 'wā'),
      FidelForm(fidel: 'ዌ', phonetic: 'wé'),
      FidelForm(fidel: 'ው', phonetic: 'we'),
      FidelForm(fidel: 'ዎ', phonetic: 'wo'),
    ],
  ),
  FidelLetter(
    base: 'ዐ',
    forms: [
      FidelForm(fidel: 'ዐ', phonetic: 'ʻa'),
      FidelForm(fidel: 'ዑ', phonetic: 'ʻu'),
      FidelForm(fidel: 'ዒ', phonetic: 'ʻi'),
      FidelForm(fidel: 'ዓ', phonetic: 'ʻā'),
      FidelForm(fidel: 'ዔ', phonetic: 'ʻé'),
      FidelForm(fidel: 'ዕ', phonetic: 'ʻe'),
      FidelForm(fidel: 'ዖ', phonetic: 'ʻo'),
    ],
  ),
  FidelLetter(
    base: 'ዘ',
    forms: [
      FidelForm(fidel: 'ዘ', phonetic: 'za'),
      FidelForm(fidel: 'ዙ', phonetic: 'zu'),
      FidelForm(fidel: 'ዚ', phonetic: 'zi'),
      FidelForm(fidel: 'ዛ', phonetic: 'zā'),
      FidelForm(fidel: 'ዜ', phonetic: 'zé'),
      FidelForm(fidel: 'ዝ', phonetic: 'ze'),
      FidelForm(fidel: 'ዞ', phonetic: 'zo'),
    ],
  ),
  FidelLetter(
    base: 'ዠ',
    forms: [
      FidelForm(fidel: 'ዠ', phonetic: 'ža'),
      FidelForm(fidel: 'ዡ', phonetic: 'žu'),
      FidelForm(fidel: 'ዢ', phonetic: 'ži'),
      FidelForm(fidel: 'ዣ', phonetic: 'žā'),
      FidelForm(fidel: 'ዤ', phonetic: 'žé'),
      FidelForm(fidel: 'ዥ', phonetic: 'že'),
      FidelForm(fidel: 'ዦ', phonetic: 'žo'),
    ],
  ),
  FidelLetter(
  base: 'የ',
  forms: [
    FidelForm(fidel: 'የ', phonetic: 'ya'),
    FidelForm(fidel: 'ዩ', phonetic: 'yu'),
    FidelForm(fidel: 'ዪ', phonetic: 'yi'),
    FidelForm(fidel: 'ያ', phonetic: 'yā'),
    FidelForm(fidel: 'ዬ', phonetic: 'yé'),
    FidelForm(fidel: 'ይ', phonetic: 'ye'),
    FidelForm(fidel: 'ዮ', phonetic: 'yo'),
  ],
),
FidelLetter(
  base: 'ደ',
  forms: [
    FidelForm(fidel: 'ደ', phonetic: 'da'),
    FidelForm(fidel: 'ዱ', phonetic: 'du'),
    FidelForm(fidel: 'ዲ', phonetic: 'di'),
    FidelForm(fidel: 'ዳ', phonetic: 'dā'),
    FidelForm(fidel: 'ዴ', phonetic: 'dé'),
    FidelForm(fidel: 'ድ', phonetic: 'de'),
    FidelForm(fidel: 'ዶ', phonetic: 'do'),
  ],
),
FidelLetter(
  base: 'ጀ',
  forms: [
    FidelForm(fidel: 'ጀ', phonetic: 'ǧa'),
    FidelForm(fidel: 'ጁ', phonetic: 'ǧu'),
    FidelForm(fidel: 'ጂ', phonetic: 'ǧi'),
    FidelForm(fidel: 'ጃ', phonetic: 'ǧā'),
    FidelForm(fidel: 'ጄ', phonetic: 'ǧé'),
    FidelForm(fidel: 'ጅ', phonetic: 'ǧe'),
    FidelForm(fidel: 'ጆ', phonetic: 'ǧo'),
  ],
),
FidelLetter(
  base: 'ገ',
  forms: [
    FidelForm(fidel: 'ገ', phonetic: 'ga'),
    FidelForm(fidel: 'ጉ', phonetic: 'gu'),
    FidelForm(fidel: 'ጊ', phonetic: 'gi'),
    FidelForm(fidel: 'ጋ', phonetic: 'gā'),
    FidelForm(fidel: 'ጌ', phonetic: 'gé'),
    FidelForm(fidel: 'ግ', phonetic: 'ge'),
    FidelForm(fidel: 'ጎ', phonetic: 'go'),
  ],
),
FidelLetter(
  base: 'ጠ',
  forms: [
    FidelForm(fidel: 'ጠ', phonetic: 'ṭa'),
    FidelForm(fidel: 'ጡ', phonetic: 'ṭu'),
    FidelForm(fidel: 'ጢ', phonetic: 'ṭi'),
    FidelForm(fidel: 'ጣ', phonetic: 'ṭā'),
    FidelForm(fidel: 'ጤ', phonetic: 'ṭé'),
    FidelForm(fidel: 'ጥ', phonetic: 'ṭe'),
    FidelForm(fidel: 'ጦ', phonetic: 'ṭo'),
  ],
),
FidelLetter(
  base: 'ጨ',
  forms: [
    FidelForm(fidel: 'ጨ', phonetic: 'ċa'),
    FidelForm(fidel: 'ጩ', phonetic: 'ċu'),
    FidelForm(fidel: 'ጪ', phonetic: 'ċi'),
    FidelForm(fidel: 'ጫ', phonetic: 'ċā'),
    FidelForm(fidel: 'ጬ', phonetic: 'ċé'),
    FidelForm(fidel: 'ጭ', phonetic: 'ċe'),
    FidelForm(fidel: 'ጮ', phonetic: 'ċo'),
  ],
),
FidelLetter(
  base: 'ጰ',
  forms: [
    FidelForm(fidel: 'ጰ', phonetic: 'p̣a'),
    FidelForm(fidel: 'ጱ', phonetic: 'p̣u'),
    FidelForm(fidel: 'ጲ', phonetic: 'p̣i'),
    FidelForm(fidel: 'ጳ', phonetic: 'p̣ā'),
    FidelForm(fidel: 'ጴ', phonetic: 'p̣é'),
    FidelForm(fidel: 'ጵ', phonetic: 'p̣e'),
    FidelForm(fidel: 'ጶ', phonetic: 'p̣o'),
  ],
),
FidelLetter(
  base: 'ጸ',
  forms: [
    FidelForm(fidel: 'ጸ', phonetic: 'ṣa'),
    FidelForm(fidel: 'ጹ', phonetic: 'ṣu'),
    FidelForm(fidel: 'ጺ', phonetic: 'ṣi'),
    FidelForm(fidel: 'ጻ', phonetic: 'ṣā'),
    FidelForm(fidel: 'ጼ', phonetic: 'ṣé'),
    FidelForm(fidel: 'ጽ', phonetic: 'ṣe'),
    FidelForm(fidel: 'ጾ', phonetic: 'ṣo'),
  ],
),
FidelLetter(
  base: 'ፀ',
  forms: [
    FidelForm(fidel: 'ፀ', phonetic: 'ṡa'),
    FidelForm(fidel: 'ፁ', phonetic: 'ṡu'),
    FidelForm(fidel: 'ፂ', phonetic: 'ṡi'),
    FidelForm(fidel: 'ፃ', phonetic: 'ṡā'),
    FidelForm(fidel: 'ፄ', phonetic: 'ṡé'),
    FidelForm(fidel: 'ፅ', phonetic: 'ṡe'),
    FidelForm(fidel: 'ፆ', phonetic: 'ṡo'),
  ],
),
FidelLetter(
  base: 'ፈ',
  forms: [
    FidelForm(fidel: 'ፈ', phonetic: 'fa'),
    FidelForm(fidel: 'ፉ', phonetic: 'fu'),
    FidelForm(fidel: 'ፊ', phonetic: 'fi'),
    FidelForm(fidel: 'ፋ', phonetic: 'fā'),
    FidelForm(fidel: 'ፌ', phonetic: 'fé'),
    FidelForm(fidel: 'ፍ', phonetic: 'fe'),
    FidelForm(fidel: 'ፎ', phonetic: 'fo'),
  ],
),
FidelLetter(
  base: 'ፐ',
  forms: [
    FidelForm(fidel: 'ፐ', phonetic: 'pa'),
    FidelForm(fidel: 'ፑ', phonetic: 'pu'),
    FidelForm(fidel: 'ፒ', phonetic: 'pi'),
    FidelForm(fidel: 'ፓ', phonetic: 'pā'),
    FidelForm(fidel: 'ፔ', phonetic: 'pé'),
    FidelForm(fidel: 'ፕ', phonetic: 'pe'),
    FidelForm(fidel: 'ፖ', phonetic: 'po'),
  ],
),
FidelLetter(
  base: 'ቨ',
  forms: [
    FidelForm(fidel: 'ቨ', phonetic: 'va'),
    FidelForm(fidel: 'ቩ', phonetic: 'vu'),
    FidelForm(fidel: 'ቪ', phonetic: 'vi'),
    FidelForm(fidel: 'ቫ', phonetic: 'vā'),
    FidelForm(fidel: 'ቬ', phonetic: 'vé'),
    FidelForm(fidel: 'ቭ', phonetic: 've'),
    FidelForm(fidel: 'ቮ', phonetic: 'vo'),
  ],
),

  // Add other base letters like , መ, ረ...
];
