import 'package:fidel/model/geez_number.dart';

class GeezNumberService {
  static List<GeezNumber> getNumbers() {
    return [
      GeezNumber(number: 1, symbol: '፩', name: 'አንድ'),
      GeezNumber(number: 2, symbol: '፪', name: 'ሁለት'),
      GeezNumber(number: 3, symbol: '፫', name: 'ሶስት'),
      GeezNumber(number: 4, symbol: '፬', name: 'አራት'),
      GeezNumber(number: 5, symbol: '፭', name: 'አምስት'),
      GeezNumber(number: 6, symbol: '፮', name: 'ስድስት'),
      GeezNumber(number: 7, symbol: '፯', name: 'ሰባት'),
      GeezNumber(number: 8, symbol: '፰', name: 'ስምንት'),
      GeezNumber(number: 9, symbol: '፱', name: 'ዘጠኝ'),
      GeezNumber(number: 10, symbol: '፲', name: 'አስር'),
      GeezNumber(number: 11, symbol: '፲፩', name: 'አስራ አንድ'),
      GeezNumber(number: 12, symbol: '፲፪', name: 'አስራ ሁለት'),
      GeezNumber(number: 13, symbol: '፲፫', name: 'አስራ ሶስት'),
      GeezNumber(number: 14, symbol: '፲፬', name: 'አስራ አራት'),
      GeezNumber(number: 15, symbol: '፲፭', name: 'አስራ አምስት'),
      GeezNumber(number: 16, symbol: '፲፮', name: 'አስራ ስድስት'),
      GeezNumber(number: 17, symbol: '፲፯', name: 'አስራ ሰባት'),
      GeezNumber(number: 18, symbol: '፲፰', name: 'አስራ ስምንት'),
      GeezNumber(number: 19, symbol: '፲፱', name: 'አስራ ዘጠኝ'),
      GeezNumber(number: 20, symbol: '፳', name: 'ሃያ'),

      GeezNumber(number: 21, symbol: '፳፩', name: 'ሃያ አንድ'),
      GeezNumber(number: 22, symbol: '፳፪', name: 'ሃያ ሁለት'),
      GeezNumber(number: 23, symbol: '፳፫', name: 'ሃያ ሶስት'),
      GeezNumber(number: 24, symbol: '፳፬', name: 'ሃያ አራት'),
      GeezNumber(number: 25, symbol: '፳፭', name: 'ሃያ አምስት'),
      GeezNumber(number: 26, symbol: '፳፮', name: 'ሃያ ስድስት'),
      GeezNumber(number: 27, symbol: '፳፯', name: 'ሃያ ሰባት'),
      GeezNumber(number: 28, symbol: '፳፰', name: 'ሃያ ስምንት'),
      GeezNumber(number: 29, symbol: '፳፱', name: 'ሃያ ዘጠኝ'),

      GeezNumber(number: 30, symbol: '፴', name: 'ሰላሳ'),
      GeezNumber(number: 31, symbol: '፴፩', name: 'ሰላሳ አንድ'),
      GeezNumber(number: 32, symbol: '፴፪', name: 'ሰላሳ ሁለት'),
      GeezNumber(number: 33, symbol: '፴፫', name: 'ሰላሳ ሶስት'),
      GeezNumber(number: 34, symbol: '፴፬', name: 'ሰላሳ አራት'),
      GeezNumber(number: 35, symbol: '፴፭', name: 'ሰላሳ አምስት'),
      GeezNumber(number: 36, symbol: '፴፮', name: 'ሰላሳ ስድስት'),
      GeezNumber(number: 37, symbol: '፴፯', name: 'ሰላሳ ሰባት'),
      GeezNumber(number: 38, symbol: '፴፰', name: 'ሰላሳ ስምንት'),
      GeezNumber(number: 39, symbol: '፴፱', name: 'ሰላሳ ዘጠኝ'),

      GeezNumber(number: 40, symbol: '፵', name: 'አርባ'),
      GeezNumber(number: 41, symbol: '፵፩', name: 'አርባ አንድ'),
      GeezNumber(number: 42, symbol: '፵፪', name: 'አርባ ሁለት'),
      GeezNumber(number: 43, symbol: '፵፫', name: 'አርባ ሶስት'),
      GeezNumber(number: 44, symbol: '፵፬', name: 'አርባ አራት'),
      GeezNumber(number: 45, symbol: '፵፭', name: 'አርባ አምስት'),
      GeezNumber(number: 46, symbol: '፵፮', name: 'አርባ ስድስት'),
      GeezNumber(number: 47, symbol: '፵፯', name: 'አርባ ሰባት'),
      GeezNumber(number: 48, symbol: '፵፰', name: 'አርባ ስምንት'),
      GeezNumber(number: 49, symbol: '፵፱', name: 'አርባ ዘጠኝ'),

      GeezNumber(number: 50, symbol: '፶', name: 'ሀምሳ'),
      GeezNumber(number: 51, symbol: '፶፩', name: 'ሀምሳ አንድ'),
      GeezNumber(number: 52, symbol: '፶፪', name: 'ሀምሳ ሁለት'),
      GeezNumber(number: 53, symbol: '፶፫', name: 'ሀምሳ ሶስት'),
      GeezNumber(number: 54, symbol: '፶፬', name: 'ሀምሳ አራት'),
      GeezNumber(number: 55, symbol: '፶፭', name: 'ሀምሳ አምስት'),
      GeezNumber(number: 56, symbol: '፶፮', name: 'ሀምሳ ስድስት'),
      GeezNumber(number: 57, symbol: '፶፯', name: 'ሀምሳ ሰባት'),
      GeezNumber(number: 58, symbol: '፶፰', name: 'ሀምሳ ስምንት'),
      GeezNumber(number: 59, symbol: '፶፱', name: 'ሀምሳ ዘጠኝ'),

      GeezNumber(number: 60, symbol: '፷', name: 'ስልሳ'),
      GeezNumber(number: 61, symbol: '፷፩', name: 'ስልሳ አንድ'),
      GeezNumber(number: 62, symbol: '፷፪', name: 'ስልሳ ሁለት'),
      GeezNumber(number: 63, symbol: '፷፫', name: 'ስልሳ ሶስት'),
      GeezNumber(number: 64, symbol: '፷፬', name: 'ስልሳ አራት'),
      GeezNumber(number: 65, symbol: '፷፭', name: 'ስልሳ አምስት'),
      GeezNumber(number: 66, symbol: '፷፮', name: 'ስልሳ ስድስት'),
      GeezNumber(number: 67, symbol: '፷፯', name: 'ስልሳ ሰባት'),
      GeezNumber(number: 68, symbol: '፷፰', name: 'ስልሳ ስምንት'),
      GeezNumber(number: 69, symbol: '፷፱', name: 'ስልሳ ዘጠኝ'),

      GeezNumber(number: 70, symbol: '፸', name: 'ሰባ'),
      GeezNumber(number: 71, symbol: '፸፩', name: 'ሰባ አንድ'),
      GeezNumber(number: 72, symbol: '፸፪', name: 'ሰባ ሁለት'),
      GeezNumber(number: 73, symbol: '፸፫', name: 'ሰባ ሶስት'),
      GeezNumber(number: 74, symbol: '፸፬', name: 'ሰባ አራት'),
      GeezNumber(number: 75, symbol: '፸፭', name: 'ሰባ አምስት'),
      GeezNumber(number: 76, symbol: '፸፮', name: 'ሰባ ስድስት'),
      GeezNumber(number: 77, symbol: '፸፯', name: 'ሰባ ሰባት'),
      GeezNumber(number: 78, symbol: '፸፰', name: 'ሰባ ስምንት'),
      GeezNumber(number: 79, symbol: '፸፱', name: 'ሰባ ዘጠኝ'),

      GeezNumber(number: 80, symbol: '፹', name: 'ሰማንያ'),
      GeezNumber(number: 81, symbol: '፹፩', name: 'ሰማንያ አንድ'),
      GeezNumber(number: 82, symbol: '፹፪', name: 'ሰማንያ ሁለት'),
      GeezNumber(number: 83, symbol: '፹፫', name: 'ሰማንያ ሶስት'),
      GeezNumber(number: 84, symbol: '፹፬', name: 'ሰማንያ አራት'),
      GeezNumber(number: 85, symbol: '፹፭', name: 'ሰማንያ አምስት'),
      GeezNumber(number: 86, symbol: '፹፮', name: 'ሰማንያ ስድስት'),
      GeezNumber(number: 87, symbol: '፹፯', name: 'ሰማንያ ሰባት'),
      GeezNumber(number: 88, symbol: '፹፰', name: 'ሰማንያ ስምንት'),
      GeezNumber(number: 89, symbol: '፹፱', name: 'ሰማንያ ዘጠኝ'),

      GeezNumber(number: 90, symbol: '፺', name: 'ዘጠና'),
      GeezNumber(number: 91, symbol: '፺፩', name: 'ዘጠና አንድ'),
      GeezNumber(number: 92, symbol: '፺፪', name: 'ዘጠና ሁለት'),
      GeezNumber(number: 93, symbol: '፺፫', name: 'ዘጠና ሶስት'),
      GeezNumber(number: 94, symbol: '፺፬', name: 'ዘጠና አራት'),
      GeezNumber(number: 95, symbol: '፺፭', name: 'ዘጠና አምስት'),
      GeezNumber(number: 96, symbol: '፺፮', name: 'ዘጠና ስድስት'),
      GeezNumber(number: 97, symbol: '፺፯', name: 'ዘጠና ሰባት'),
      GeezNumber(number: 98, symbol: '፺፰', name: 'ዘጠና ስምንት'),
      GeezNumber(number: 99, symbol: '፺፱', name: 'ዘጠና ዘጠኝ'),
      GeezNumber(number: 100, symbol: '፻', name: 'መቶ'),
      GeezNumber(number: 200, symbol: '፪፻', name: 'ሁለት መቶ'),
      GeezNumber(number: 500, symbol: '፭፻', name: 'አምስት መቶ'),
      GeezNumber(number: 1000, symbol: '፲፻', name: 'ሺህ'),
       GeezNumber(number: 1900, symbol: '፲፱፻', name: 'አንድ ሺ ዘጠኝ መቶ'),
      GeezNumber(number: 1901, symbol: '፲፱፻፩', name: 'አንድ ሺ ዘጠኝ መቶ አንድ'),
      GeezNumber(number: 1902, symbol: '፲፱፻፪', name: 'አንድ ሺ ዘጠኝ መቶ ሁለት'),
      GeezNumber(number: 1903, symbol: '፲፱፻፫', name: 'አንድ ሺ ዘጠኝ መቶ ሶስት'),
      GeezNumber(number: 1904, symbol: '፲፱፻፬', name: 'አንድ ሺ ዘጠኝ መቶ አራት'),
      GeezNumber(number: 1905, symbol: '፲፱፻፭', name: 'አንድ ሺ ዘጠኝ መቶ አምስት'),
      GeezNumber(number: 1906, symbol: '፲፱፻፮', name: 'አንድ ሺ ዘጠኝ መቶ ስድስት'),
      GeezNumber(number: 1907, symbol: '፲፱፻፯', name: 'አንድ ሺ ዘጠኝ መቶ ሰባት'),
      GeezNumber(number: 1908, symbol: '፲፱፻፰', name: 'አንድ ሺ ዘጠኝ መቶ ስምንት'),
      GeezNumber(number: 1909, symbol: '፲፱፻፱', name: 'አንድ ሺ ዘጠኝ መቶ ዘጠኝ'),

      GeezNumber(number: 1910, symbol: '፲፱፻፲', name: 'አንድ ሺ ዘጠኝ መቶ አስር'),
      GeezNumber(number: 1911, symbol: '፲፱፻፲፩', name: 'አንድ ሺ ዘጠኝ መቶ አስራ አንድ'),
      GeezNumber(number: 1912, symbol: '፲፱፻፲፪', name: 'አንድ ሺ ዘጠኝ መቶ አስራ ሁለት'),
      GeezNumber(number: 1913, symbol: '፲፱፻፲፫', name: 'አንድ ሺ ዘጠኝ መቶ አስራ ሶስት'),
      GeezNumber(number: 1914, symbol: '፲፱፻፲፬', name: 'አንድ ሺ ዘጠኝ መቶ አስራ አራት'),
      GeezNumber(number: 1915, symbol: '፲፱፻፲፭', name: 'አንድ ሺ ዘጠኝ መቶ አስራ አምስት'),
      GeezNumber(number: 1916, symbol: '፲፱፻፲፮', name: 'አንድ ሺ ዘጠኝ መቶ አስራ ስድስት'),
      GeezNumber(number: 1917, symbol: '፲፱፻፲፯', name: 'አንድ ሺ ዘጠኝ መቶ አስራ ሰባት'),
      GeezNumber(number: 1918, symbol: '፲፱፻፲፰', name: 'አንድ ሺ ዘጠኝ መቶ አስራ ስምንት'),
      GeezNumber(number: 1919, symbol: '፲፱፻፲፱', name: 'አንድ ሺ ዘጠኝ መቶ አስራ ዘጠኝ'),
      
      GeezNumber(number: 2020, symbol: '፳፻፳', name: 'ሁለት ሺ ሃያ'),
      GeezNumber(number: 2021, symbol: '፳፻፳፩', name: 'ሁለት ሺ ሃያ አንድ'),
      GeezNumber(number: 2022, symbol: '፳፻፳፪', name: 'ሁለት ሺ ሃያ ሁለት'),
      GeezNumber(number: 2023, symbol: '፳፻፳፫', name: 'ሁለት ሺ ሃያ ሶስት'),
      GeezNumber(number: 2024, symbol: '፳፻፳፬', name: 'ሁለት ሺ ሃያ አራት'),
      GeezNumber(number: 2025, symbol: '፳፻፳፭', name: 'ሁለት ሺ ሃያ አምስት'),
      GeezNumber(number: 2026, symbol: '፳፻፳፮', name: 'ሁለት ሺ ሃያ ስድስት'),
      GeezNumber(number: 2027, symbol: '፳፻፳፯', name: 'ሁለት ሺ ሃያ ሰባት'),
      GeezNumber(number: 2028, symbol: '፳፻፳፰', name: 'ሁለት ሺ ሃያ ስምንት'),
      GeezNumber(number: 2029, symbol: '፳፻፳፱', name: 'ሁለት ሺ ሃያ ዘጠኝ'),
      GeezNumber(number: 2030, symbol: '፳፻፴', name: 'ሁለት ሺ ሰላሳ'),
      GeezNumber(
          number: 10000,
          symbol: '፲፼',
          name: 'እልፍ'), // Geez symbol for 10,000 is ፲፼ (10 * 1000)
      GeezNumber(number: 100000, symbol: '፻፼', name: 'አስር እልፍ'), // 100 * 10000
      GeezNumber(number: 1000000, symbol: '፲፻፼', name: 'ሚሊዮን'), // 1000 * 10000
    ];
  }
}
